"""
Extended Document Type Definitions
Comprehensive collection of corporate and legal document templates
"""

# Additional document types organized by category
ADDITIONAL_DOCUMENT_TYPES = {
    # ===== REAL ESTATE & PROPERTY =====
    "Commercial Lease Agreement": [
        {"key": "landlord", "label": "Landlord Name", "type": "text", "placeholder": "ABC Properties LLC", "help": "Property owner"},
        {"key": "tenant", "label": "Tenant Name", "type": "text", "placeholder": "XYZ Business Inc.", "help": "Business renting the property"},
        {"key": "property_address", "label": "Property Address", "type": "textarea", "placeholder": "123 Main Street, Suite 500, City, State, ZIP", "help": "Full address of leased space"},
        {"key": "square_footage", "label": "Square Footage", "type": "number", "placeholder": "5000", "help": "Size of leased space"},
        {"key": "permitted_use", "label": "Permitted Use", "type": "textarea", "placeholder": "General office use only", "help": "What tenant can use space for"},
        {"key": "lease_term", "label": "Lease Term", "type": "text", "placeholder": "5 years", "help": "Length of lease"},
        {"key": "start_date", "label": "Start Date", "type": "date", "help": "When lease begins"},
        {"key": "base_rent", "label": "Base Monthly Rent", "type": "text", "placeholder": "$15,000", "help": "Monthly rent amount"},
        {"key": "rent_increases", "label": "Rent Increases", "type": "text", "placeholder": "3% annually", "help": "Rent escalation schedule"},
        {"key": "security_deposit", "label": "Security Deposit", "type": "text", "placeholder": "$30,000 (2 months rent)", "help": "Deposit amount"},
        {"key": "operating_expenses", "label": "Operating Expenses", "type": "textarea", "placeholder": "Tenant pays pro-rata share of property taxes, insurance, CAM", "help": "Additional costs beyond base rent"},
        {"key": "utilities", "label": "Utilities", "type": "text", "placeholder": "Tenant responsible for electricity, internet", "help": "Who pays for utilities"},
        {"key": "maintenance", "label": "Maintenance Responsibilities", "type": "textarea", "placeholder": "Landlord: roof, structure; Tenant: interior repairs", "help": "Who maintains what"},
        {"key": "improvements", "label": "Tenant Improvements", "type": "textarea", "placeholder": "$50,000 improvement allowance, landlord approval required", "help": "Allowed modifications"},
        {"key": "renewal_option", "label": "Renewal Options", "type": "text", "placeholder": "Two 5-year renewal options at market rate", "help": "Ability to extend lease"},
        {"key": "early_termination", "label": "Early Termination", "type": "textarea", "placeholder": "6 months notice + termination fee", "help": "How lease can be ended early"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of California", "help": "Applicable jurisdiction"},
    ],
    "Residential Lease Agreement": [
        {"key": "landlord", "label": "Landlord Name", "type": "text", "placeholder": "John Smith", "help": "Property owner"},
        {"key": "tenant", "label": "Tenant Name(s)", "type": "textarea", "placeholder": "Jane Doe, Bob Johnson", "help": "All tenants on the lease"},
        {"key": "property_address", "label": "Property Address", "type": "textarea", "placeholder": "456 Oak Street, Apt 3B, City, State, ZIP", "help": "Full rental property address"},
        {"key": "lease_term", "label": "Lease Term", "type": "text", "placeholder": "12 months", "help": "Length of lease"},
        {"key": "start_date", "label": "Start Date", "type": "date", "help": "Move-in date"},
        {"key": "end_date", "label": "End Date", "type": "date", "help": "Lease expiration date"},
        {"key": "monthly_rent", "label": "Monthly Rent", "type": "text", "placeholder": "$2,500", "help": "Rent amount per month"},
        {"key": "due_date", "label": "Rent Due Date", "type": "text", "placeholder": "1st of each month", "help": "When rent is due"},
        {"key": "late_fee", "label": "Late Fee", "type": "text", "placeholder": "$50 if paid after 5th of month", "help": "Penalty for late payment"},
        {"key": "security_deposit", "label": "Security Deposit", "type": "text", "placeholder": "$2,500", "help": "Deposit amount"},
        {"key": "utilities", "label": "Utility Responsibilities", "type": "textarea", "placeholder": "Tenant pays electricity, gas, internet; Landlord pays water, trash", "help": "Who pays for utilities"},
        {"key": "occupants", "label": "Maximum Occupants", "type": "number", "placeholder": "4", "help": "Maximum number of people allowed"},
        {"key": "pets", "label": "Pet Policy", "type": "text", "placeholder": "One small dog allowed with $500 pet deposit", "help": "Rules about pets"},
        {"key": "maintenance", "label": "Maintenance and Repairs", "type": "textarea", "placeholder": "Tenant responsible for minor repairs under $100", "help": "Repair responsibilities"},
        {"key": "rules", "label": "House Rules", "type": "textarea", "placeholder": "Quiet hours 10pm-8am, no smoking, lawn care required", "help": "Property rules and regulations"},
        {"key": "renewal", "label": "Renewal Terms", "type": "text", "placeholder": "60-day notice required, rent subject to increase", "help": "How to renew lease"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Florida", "help": "Applicable jurisdiction"},
    ],
    "Purchase and Sale Agreement (Real Estate)": [
        {"key": "seller", "label": "Seller Name(s)", "type": "text", "placeholder": "John and Mary Smith", "help": "Current property owner(s)"},
        {"key": "buyer", "label": "Buyer Name(s)", "type": "text", "placeholder": "Bob and Alice Johnson", "help": "Purchaser(s)"},
        {"key": "property_address", "label": "Property Address", "type": "textarea", "placeholder": "789 Maple Drive, City, State, ZIP", "help": "Full legal address"},
        {"key": "legal_description", "label": "Legal Description", "type": "textarea", "placeholder": "Lot 5, Block 12, Green Valley Subdivision", "help": "Official property description"},
        {"key": "purchase_price", "label": "Purchase Price", "type": "text", "placeholder": "$650,000", "help": "Total sale price"},
        {"key": "earnest_money", "label": "Earnest Money Deposit", "type": "text", "placeholder": "$10,000", "help": "Good faith deposit"},
        {"key": "down_payment", "label": "Down Payment", "type": "text", "placeholder": "$130,000 (20%)", "help": "Cash down payment amount"},
        {"key": "financing", "label": "Financing Details", "type": "textarea", "placeholder": "Conventional loan, 30-year fixed, pre-approved", "help": "How purchase is financed"},
        {"key": "closing_date", "label": "Target Closing Date", "type": "date", "help": "Expected closing date"},
        {"key": "contingencies", "label": "Contingencies", "type": "textarea", "placeholder": "Financing approval, satisfactory home inspection, clear title", "help": "Conditions that must be met"},
        {"key": "inspection_period", "label": "Inspection Period", "type": "text", "placeholder": "14 days", "help": "Time for buyer to inspect property"},
        {"key": "included_items", "label": "Included Items", "type": "textarea", "placeholder": "All appliances, window treatments, ceiling fans", "help": "What stays with property"},
        {"key": "excluded_items", "label": "Excluded Items", "type": "textarea", "placeholder": "Chandelier in dining room, garden shed", "help": "What seller is taking"},
        {"key": "disclosures", "label": "Seller Disclosures", "type": "textarea", "placeholder": "Roof replaced 2020, basement floods in heavy rain", "help": "Known property issues"},
        {"key": "closing_costs", "label": "Closing Cost Allocation", "type": "textarea", "placeholder": "Seller pays title insurance, buyer pays recording fees", "help": "Who pays which closing costs"},
        {"key": "possession", "label": "Possession Date", "type": "date", "help": "When buyer takes possession"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Arizona", "help": "Applicable jurisdiction"},
    ],
    "Property Management Agreement": [
        {"key": "owner", "label": "Property Owner", "type": "text", "placeholder": "ABC Investment Properties LLC", "help": "Owner of the property"},
        {"key": "manager", "label": "Property Manager", "type": "text", "placeholder": "ProManage Real Estate", "help": "Management company"},
        {"key": "property_address", "label": "Property Address", "type": "textarea", "placeholder": "123 Rental Street, City, State", "help": "Property being managed"},
        {"key": "property_type", "label": "Property Type", "type": "text", "placeholder": "20-unit apartment building", "help": "Type and size of property"},
        {"key": "management_fee", "label": "Management Fee", "type": "text", "placeholder": "8% of gross collected rent", "help": "Monthly management fee"},
        {"key": "leasing_fee", "label": "Leasing Fee", "type": "text", "placeholder": "One month's rent per new lease", "help": "Fee for finding new tenants"},
        {"key": "maintenance_authority", "label": "Maintenance Authority", "type": "textarea", "placeholder": "Manager can authorize repairs up to $500 without approval", "help": "Manager's spending limit"},
        {"key": "services_provided", "label": "Management Services", "type": "textarea", "placeholder": "Rent collection, tenant screening, maintenance coordination, financial reporting", "help": "What manager will do"},
        {"key": "owner_responsibilities", "label": "Owner Responsibilities", "type": "textarea", "placeholder": "Maintain insurance, approve major repairs, provide operating funds", "help": "What owner must do"},
        {"key": "rent_collection", "label": "Rent Collection", "type": "textarea", "placeholder": "Collect rent, enforce late fees, handle evictions", "help": "Rent collection procedures"},
        {"key": "reporting", "label": "Financial Reporting", "type": "text", "placeholder": "Monthly income/expense statements, annual tax summaries", "help": "Reports manager will provide"},
        {"key": "tenant_selection", "label": "Tenant Selection Criteria", "type": "textarea", "placeholder": "Credit check, employment verification, rental history", "help": "How tenants are screened"},
        {"key": "term", "label": "Agreement Term", "type": "text", "placeholder": "12 months, auto-renewing", "help": "Length of management agreement"},
        {"key": "termination", "label": "Termination Notice", "type": "text", "placeholder": "90 days written notice", "help": "How to end agreement"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Nevada", "help": "Applicable jurisdiction"},
    ],
    # ===== INTELLECTUAL PROPERTY =====
    "Patent Assignment Agreement": [
        {"key": "assignor", "label": "Assignor Name", "type": "text", "placeholder": "Dr. Jane Inventor", "help": "Person/entity transferring patent rights"},
        {"key": "assignee", "label": "Assignee Name", "type": "text", "placeholder": "Innovation Corp", "help": "Person/entity receiving patent rights"},
        {"key": "invention_title", "label": "Invention Title", "type": "text", "placeholder": "Advanced Widget Manufacturing Process", "help": "Name of the invention"},
        {"key": "patent_numbers", "label": "Patent Number(s)", "type": "textarea", "placeholder": "US Patent No. 10,123,456; Application No. 16/789,012", "help": "Issued patent and/or application numbers"},
        {"key": "filing_date", "label": "Filing Date", "type": "date", "help": "When patent application was filed"},
        {"key": "invention_description", "label": "Invention Description", "type": "textarea", "placeholder": "Brief description of the patented technology", "help": "What the invention covers"},
        {"key": "consideration", "label": "Consideration", "type": "text", "placeholder": "$50,000 + royalties", "help": "Payment for assignment"},
        {"key": "royalty_terms", "label": "Royalty Terms (if applicable)", "type": "textarea", "placeholder": "5% of net sales", "help": "Ongoing royalty payments"},
        {"key": "assignment_scope", "label": "Assignment Scope", "type": "textarea", "placeholder": "All rights, title, and interest worldwide", "help": "What rights are transferred"},
        {"key": "warranties", "label": "Assignor Warranties", "type": "textarea", "placeholder": "Sole inventor, no conflicting agreements, valid and enforceable", "help": "Promises about the patent"},
        {"key": "cooperation", "label": "Post-Assignment Cooperation", "type": "textarea", "placeholder": "Assignor will assist with prosecution, litigation as needed", "help": "Ongoing assistance obligations"},
        {"key": "effective_date", "label": "Effective Date", "type": "date", "help": "When assignment takes effect"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of California", "help": "Applicable jurisdiction"},
    ],
    "Trademark License Agreement": [
        {"key": "licensor", "label": "Licensor Name", "type": "text", "placeholder": "BrandCo Inc.", "help": "Trademark owner"},
        {"key": "licensee", "label": "Licensee Name", "type": "text", "placeholder": "Retailer LLC", "help": "Party receiving license"},
        {"key": "trademark", "label": "Trademark", "type": "text", "placeholder": "BRANDNAME®", "help": "Trademark being licensed"},
        {"key": "registration_numbers", "label": "Registration Numbers", "type": "textarea", "placeholder": "US Reg. No. 5,123,456; EU No. 018123456", "help": "Trademark registration details"},
        {"key": "licensed_products", "label": "Licensed Products/Services", "type": "textarea", "placeholder": "Apparel, footwear, accessories", "help": "What products can bear the trademark"},
        {"key": "territory", "label": "Territory", "type": "text", "placeholder": "United States and Canada", "help": "Geographic scope of license"},
        {"key": "exclusivity", "label": "Exclusivity", "type": "text", "placeholder": "Exclusive / Non-exclusive", "help": "Is this the only license?"},
        {"key": "license_term", "label": "License Term", "type": "text", "placeholder": "5 years", "help": "Duration of license"},
        {"key": "royalty_rate", "label": "Royalty Rate", "type": "text", "placeholder": "8% of net sales", "help": "Payment to licensor"},
        {"key": "minimum_royalty", "label": "Minimum Guaranteed Royalty", "type": "text", "placeholder": "$100,000 annually", "help": "Minimum payment regardless of sales"},
        {"key": "payment_schedule", "label": "Payment Schedule", "type": "text", "placeholder": "Quarterly within 30 days of quarter end", "help": "When royalties are paid"},
        {"key": "quality_control", "label": "Quality Control Standards", "type": "textarea", "placeholder": "All products must meet licensor's quality standards, subject to approval", "help": "Quality requirements"},
        {"key": "marketing", "label": "Marketing Requirements", "type": "textarea", "placeholder": "Minimum $50,000 annual marketing spend", "help": "Promotion obligations"},
        {"key": "termination", "label": "Termination Rights", "type": "textarea", "placeholder": "Material breach, bankruptcy, failure to meet minimum royalties", "help": "When license can end"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of New York", "help": "Applicable jurisdiction"},
    ],
    "Copyright Assignment": [
        {"key": "assignor", "label": "Assignor Name", "type": "text", "placeholder": "Jane Author", "help": "Copyright creator/owner"},
        {"key": "assignee", "label": "Assignee Name", "type": "text", "placeholder": "Publishing House Inc.", "help": "Party receiving copyright"},
        {"key": "work_title", "label": "Work Title", "type": "text", "placeholder": "The Complete Guide to Widget Design", "help": "Name of copyrighted work"},
        {"key": "work_description", "label": "Work Description", "type": "textarea", "placeholder": "Technical manual including text, illustrations, and photographs", "help": "Description of the work"},
        {"key": "work_type", "label": "Type of Work", "type": "text", "placeholder": "Literary work, Software, Musical composition, etc.", "help": "Category of copyrighted work"},
        {"key": "creation_date", "label": "Creation Date", "type": "date", "help": "When work was created"},
        {"key": "registration_number", "label": "Copyright Registration No.", "type": "text", "placeholder": "TXu 2-123-456", "help": "If registered with Copyright Office"},
        {"key": "rights_assigned", "label": "Rights Being Assigned", "type": "textarea", "placeholder": "All copyright, including reproduction, distribution, derivative works, public display", "help": "Scope of assignment"},
        {"key": "territory", "label": "Territory", "type": "text", "placeholder": "Worldwide", "help": "Geographic scope"},
        {"key": "consideration", "label": "Consideration", "type": "text", "placeholder": "$25,000 + 10% royalties", "help": "Payment for assignment"},
        {"key": "royalty_terms", "label": "Royalty Terms", "type": "textarea", "placeholder": "10% of net receipts, paid quarterly", "help": "Ongoing payments if applicable"},
        {"key": "warranties", "label": "Assignor Warranties", "type": "textarea", "placeholder": "Original work, sole author, no infringement, no conflicting rights", "help": "Promises about the work"},
        {"key": "moral_rights", "label": "Moral Rights Waiver", "type": "text", "placeholder": "Assignor waives moral rights to extent permitted by law", "help": "Attribution and integrity rights"},
        {"key": "effective_date", "label": "Effective Date", "type": "date", "help": "When assignment takes effect"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of California", "help": "Applicable jurisdiction"},
    ],
    "Software License Agreement": [
        {"key": "licensor", "label": "Licensor Name", "type": "text", "placeholder": "SoftwareCo Inc.", "help": "Software owner/developer"},
        {"key": "licensee", "label": "Licensee Name", "type": "text", "placeholder": "Customer Corporation", "help": "Party receiving license"},
        {"key": "software_name", "label": "Software Name", "type": "text", "placeholder": "ProManager Enterprise Suite", "help": "Name of the software"},
        {"key": "software_version", "label": "Version", "type": "text", "placeholder": "Version 5.2", "help": "Software version being licensed"},
        {"key": "license_type", "label": "License Type", "type": "text", "placeholder": "Perpetual / Subscription / Site License", "help": "Type of license granted"},
        {"key": "number_of_users", "label": "Number of Users/Seats", "type": "number", "placeholder": "50", "help": "How many users can access"},
        {"key": "permitted_use", "label": "Permitted Use", "type": "textarea", "placeholder": "Internal business purposes only, not for resale or service bureau", "help": "Allowed uses of software"},
        {"key": "restrictions", "label": "Use Restrictions", "type": "textarea", "placeholder": "No reverse engineering, modification, or sublicensing", "help": "What licensee cannot do"},
        {"key": "license_fee", "label": "License Fee", "type": "text", "placeholder": "$50,000 annually / $150,000 perpetual", "help": "Cost of license"},
        {"key": "payment_terms", "label": "Payment Terms", "type": "text", "placeholder": "Net 30 days", "help": "When payment is due"},
        {"key": "maintenance", "label": "Maintenance and Support", "type": "textarea", "placeholder": "Includes updates, patches, email support 20% annual fee", "help": "Support services included"},
        {"key": "updates", "label": "Software Updates", "type": "text", "placeholder": "Automatic updates included / Optional", "help": "How updates are handled"},
        {"key": "warranty", "label": "Warranty", "type": "textarea", "placeholder": "90-day warranty that software operates as documented", "help": "Licensor's guarantees"},
        {"key": "liability_limit", "label": "Liability Limitation", "type": "text", "placeholder": "Limited to fees paid in past 12 months", "help": "Cap on damages"},
        {"key": "term", "label": "License Term", "type": "text", "placeholder": "12 months, auto-renewing / Perpetual", "help": "Duration of license"},
        {"key": "termination", "label": "Termination", "type": "textarea", "placeholder": "30-day notice, immediately for breach", "help": "How license can end"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Washington", "help": "Applicable jurisdiction"},
    ],
    # ===== LITIGATION & COURT =====
    "Settlement Agreement": [
        {"key": "plaintiff", "label": "Plaintiff/Claimant", "type": "text", "placeholder": "John Doe", "help": "Party bringing the claim"},
        {"key": "defendant", "label": "Defendant/Respondent", "type": "text", "placeholder": "ABC Corporation", "help": "Party defending against claim"},
        {"key": "case_caption", "label": "Case Caption", "type": "text", "placeholder": "Doe v. ABC Corporation", "help": "Name of the legal case"},
        {"key": "case_number", "label": "Case Number", "type": "text", "placeholder": "Case No. 2024-CV-12345", "help": "Court case number if filed"},
        {"key": "court", "label": "Court", "type": "text", "placeholder": "Superior Court, County of Los Angeles", "help": "Court where case is filed"},
        {"key": "dispute_description", "label": "Dispute Description", "type": "textarea", "placeholder": "Employment discrimination claim", "help": "Brief description of the dispute"},
        {"key": "settlement_amount", "label": "Settlement Payment", "type": "text", "placeholder": "$125,000", "help": "Total settlement amount"},
        {"key": "payment_schedule", "label": "Payment Schedule", "type": "textarea", "placeholder": "Lump sum within 30 days of execution / Monthly installments", "help": "How and when payment is made"},
        {"key": "non_monetary_terms", "label": "Non-Monetary Terms", "type": "textarea", "placeholder": "Neutral reference, reinstatement, policy changes, etc.", "help": "Other settlement terms"},
        {"key": "release_scope", "label": "Release of Claims", "type": "textarea", "placeholder": "Full and final release of all claims, known and unknown", "help": "What claims are being waived"},
        {"key": "confidentiality", "label": "Confidentiality Terms", "type": "textarea", "placeholder": "Settlement terms are confidential, non-disclosure required", "help": "Restrictions on disclosure"},
        {"key": "non_disparagement", "label": "Non-Disparagement", "type": "text", "placeholder": "Mutual agreement not to make negative public statements", "help": "Restrictions on public comments"},
        {"key": "dismissal", "label": "Case Dismissal", "type": "text", "placeholder": "With prejudice / Without prejudice", "help": "How court case will be dismissed"},
        {"key": "no_admission", "label": "No Admission of Liability", "type": "text", "placeholder": "Settlement not admission of wrongdoing", "help": "Liability disclaimer"},
        {"key": "effective_date", "label": "Effective Date", "type": "date", "help": "When agreement becomes effective"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of California", "help": "Applicable jurisdiction"},
    ],
    "Retainer Agreement (Legal Services)": [
        {"key": "law_firm", "label": "Law Firm/Attorney Name", "type": "text", "placeholder": "Smith & Associates LLP", "help": "Legal services provider"},
        {"key": "client", "label": "Client Name", "type": "text", "placeholder": "John Doe", "help": "Person/entity receiving legal services"},
        {"key": "matter_description", "label": "Matter Description", "type": "textarea", "placeholder": "Defense in breach of contract litigation", "help": "Legal matter being handled"},
        {"key": "services", "label": "Services to be Provided", "type": "textarea", "placeholder": "Legal research, court appearances, negotiations, document drafting", "help": "What attorney will do"},
        {"key": "fee_structure", "label": "Fee Structure", "type": "text", "placeholder": "Hourly / Flat fee / Contingency", "help": "How fees are calculated"},
        {"key": "hourly_rates", "label": "Hourly Rates", "type": "textarea", "placeholder": "Partner: $500/hr, Associate: $300/hr, Paralegal: $150/hr", "help": "Rates for different professionals"},
        {"key": "retainer_amount", "label": "Initial Retainer", "type": "text", "placeholder": "$25,000", "help": "Upfront deposit"},
        {"key": "billing_cycle", "label": "Billing Cycle", "type": "text", "placeholder": "Monthly", "help": "How often client is billed"},
        {"key": "expenses", "label": "Expenses and Costs", "type": "textarea", "placeholder": "Court fees, expert witnesses, travel expenses billed separately", "help": "Additional costs beyond fees"},
        {"key": "client_responsibilities", "label": "Client Responsibilities", "type": "textarea", "placeholder": "Provide information, respond timely, attend depositions", "help": "What client must do"},
        {"key": "attorney_responsibilities", "label": "Attorney Responsibilities", "type": "textarea", "placeholder": "Competent representation, keep client informed, maintain confidentiality", "help": "Attorney's obligations"},
        {"key": "conflicts", "label": "Conflicts of Interest", "type": "textarea", "placeholder": "No current conflicts, client waives potential future conflicts", "help": "Disclosure of conflicts"},
        {"key": "scope_limitations", "label": "Scope Limitations", "type": "textarea", "placeholder": "Limited to defense of current lawsuit, does not include appeals", "help": "What attorney will NOT do"},
        {"key": "termination", "label": "Termination", "type": "textarea", "placeholder": "Either party may terminate with written notice, client pays for work done", "help": "How engagement can end"},
        {"key": "file_retention", "label": "File Retention", "type": "text", "placeholder": "Files retained for 7 years after matter closes", "help": "How long files are kept"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Texas", "help": "Applicable jurisdiction"},
    ],
    # ===== FINANCIAL & INVESTMENT =====
    "Promissory Note": [
        {"key": "borrower", "label": "Borrower Name", "type": "text", "placeholder": "John Doe", "help": "Person/entity borrowing money"},
        {"key": "lender", "label": "Lender Name", "type": "text", "placeholder": "Jane Smith", "help": "Person/entity lending money"},
        {"key": "principal_amount", "label": "Principal Amount", "type": "text", "placeholder": "$100,000", "help": "Amount being borrowed"},
        {"key": "interest_rate", "label": "Interest Rate", "type": "text", "placeholder": "5% per annum", "help": "Annual interest rate"},
        {"key": "loan_date", "label": "Loan Date", "type": "date", "help": "When money is advanced"},
        {"key": "maturity_date", "label": "Maturity Date", "type": "date", "help": "When loan must be repaid in full"},
        {"key": "payment_schedule", "label": "Payment Schedule", "type": "textarea", "placeholder": "Monthly payments of $2,200 starting Feb 1, 2024", "help": "Repayment terms"},
        {"key": "late_fee", "label": "Late Payment Fee", "type": "text", "placeholder": "5% of late payment", "help": "Penalty for late payment"},
        {"key": "prepayment", "label": "Prepayment Terms", "type": "text", "placeholder": "May prepay without penalty / 2% prepayment penalty", "help": "Early payoff terms"},
        {"key": "security", "label": "Security/Collateral", "type": "textarea", "placeholder": "Secured by real property at 123 Main St / Unsecured", "help": "What secures the loan"},
        {"key": "default", "label": "Default Provisions", "type": "textarea", "placeholder": "Default if payment 30 days late, entire balance becomes due", "help": "What constitutes default"},
        {"key": "acceleration", "label": "Acceleration Clause", "type": "text", "placeholder": "Upon default, entire balance immediately due", "help": "Full amount due on default"},
        {"key": "attorney_fees", "label": "Attorney Fees", "type": "text", "placeholder": "Borrower pays lender's collection costs", "help": "Who pays legal fees"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Nevada", "help": "Applicable jurisdiction"},
    ],
    "Loan Agreement": [
        {"key": "lender", "label": "Lender Name", "type": "text", "placeholder": "First National Bank", "help": "Institution or person providing loan"},
        {"key": "borrower", "label": "Borrower Name", "type": "text", "placeholder": "ABC Corporation", "help": "Person/entity receiving loan"},
        {"key": "loan_amount", "label": "Loan Amount", "type": "text", "placeholder": "$500,000", "help": "Total amount being loaned"},
        {"key": "loan_purpose", "label": "Loan Purpose", "type": "textarea", "placeholder": "Working capital, equipment purchase, real estate acquisition", "help": "What loan proceeds will be used for"},
        {"key": "interest_rate", "label": "Interest Rate", "type": "text", "placeholder": "Prime + 2% / 6.5% fixed", "help": "Interest rate terms"},
        {"key": "loan_term", "label": "Loan Term", "type": "text", "placeholder": "60 months", "help": "Length of loan"},
        {"key": "repayment_schedule", "label": "Repayment Schedule", "type": "textarea", "placeholder": "Monthly payments of $9,500, 60 payments", "help": "Payment schedule"},
        {"key": "security", "label": "Security/Collateral", "type": "textarea", "placeholder": "First lien on all business assets, personal guarantee", "help": "What secures the loan"},
        {"key": "fees", "label": "Fees", "type": "textarea", "placeholder": "Origination fee: 1%, Late fee: $100", "help": "Additional fees and charges"},
        {"key": "covenants", "label": "Financial Covenants", "type": "textarea", "placeholder": "Maintain debt-to-equity ratio below 2:1, minimum working capital of $100K", "help": "Financial requirements borrower must maintain"},
        {"key": "representations", "label": "Borrower Representations", "type": "textarea", "placeholder": "Financial statements accurate, no pending litigation, in good standing", "help": "Promises borrower makes"},
        {"key": "default_events", "label": "Events of Default", "type": "textarea", "placeholder": "Missed payment, breach of covenant, bankruptcy, material adverse change", "help": "What triggers default"},
        {"key": "remedies", "label": "Lender Remedies", "type": "textarea", "placeholder": "Accelerate loan, foreclose on collateral, pursue guarantor", "help": "What lender can do upon default"},
        {"key": "prepayment", "label": "Prepayment Terms", "type": "text", "placeholder": "Permitted after 12 months with 1% penalty", "help": "Early payoff rules"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Delaware", "help": "Applicable jurisdiction"},
    ],
    "Investment Agreement (SAFE/Convertible Note)": [
        {"key": "company", "label": "Company Name", "type": "text", "placeholder": "StartupCo Inc.", "help": "Company receiving investment"},
        {"key": "investor", "label": "Investor Name", "type": "text", "placeholder": "Angel Investor LLC", "help": "Person/entity making investment"},
        {"key": "instrument_type", "label": "Instrument Type", "type": "text", "placeholder": "SAFE / Convertible Note / Equity", "help": "Type of investment instrument"},
        {"key": "investment_amount", "label": "Investment Amount", "type": "text", "placeholder": "$250,000", "help": "Amount being invested"},
        {"key": "valuation_cap", "label": "Valuation Cap", "type": "text", "placeholder": "$5,000,000", "help": "Maximum valuation for conversion (SAFE)"},
        {"key": "discount", "label": "Discount Rate", "type": "text", "placeholder": "20%", "help": "Discount on next round price"},
        {"key": "interest_rate", "label": "Interest Rate (if Note)", "type": "text", "placeholder": "5% per annum", "help": "Interest rate for convertible note"},
        {"key": "maturity_date", "label": "Maturity Date (if Note)", "type": "date", "help": "When note must convert or be repaid"},
        {"key": "conversion_triggers", "label": "Conversion Triggers", "type": "textarea", "placeholder": "Qualified financing ($1M+ at $8M+ valuation), acquisition, IPO", "help": "Events triggering conversion"},
        {"key": "pro_rata_rights", "label": "Pro-Rata Rights", "type": "text", "placeholder": "Right to participate in future rounds", "help": "Future investment rights"},
        {"key": "information_rights", "label": "Information Rights", "type": "textarea", "placeholder": "Quarterly financials, annual audited statements", "help": "Reporting to investor"},
        {"key": "use_of_proceeds", "label": "Use of Proceeds", "type": "textarea", "placeholder": "Product development, marketing, hiring", "help": "How company will use the money"},
        {"key": "representations", "label": "Company Representations", "type": "textarea", "placeholder": "Properly incorporated, authorized, no conflicts, accurate financials", "help": "Promises company makes"},
        {"key": "most_favored_nation", "label": "Most Favored Nation", "type": "text", "placeholder": "Right to same terms as future SAFEs", "help": "MFN clause"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Delaware", "help": "Applicable jurisdiction"},
    ],
    # ===== GENERAL / OTHER =====
    "Power of Attorney": [
        {"key": "principal", "label": "Principal Name", "type": "text", "placeholder": "John Doe", "help": "Person granting authority"},
        {"key": "agent", "label": "Agent/Attorney-in-Fact", "type": "text", "placeholder": "Jane Smith", "help": "Person receiving authority"},
        {"key": "alternate_agent", "label": "Alternate Agent (optional)", "type": "text", "placeholder": "Bob Johnson", "help": "Backup agent"},
        {"key": "poa_type", "label": "Type of Power of Attorney", "type": "text", "placeholder": "General / Limited / Durable / Healthcare", "help": "Scope of authority"},
        {"key": "powers_granted", "label": "Powers Granted", "type": "textarea", "placeholder": "Real estate, banking, legal proceedings, business operations", "help": "Specific authorities being granted"},
        {"key": "limitations", "label": "Limitations", "type": "textarea", "placeholder": "Cannot make gifts over $10,000, cannot change beneficiaries", "help": "Restrictions on agent's authority"},
        {"key": "effective_date", "label": "Effective Date", "type": "date", "help": "When POA becomes effective"},
        {"key": "durability", "label": "Durable (Survives Incapacity)", "type": "text", "placeholder": "Yes / No", "help": "Remains effective if principal becomes incapacitated"},
        {"key": "springing", "label": "Springing POA", "type": "textarea", "placeholder": "Takes effect only upon principal's incapacity", "help": "Conditional effectiveness"},
        {"key": "expiration", "label": "Expiration", "type": "text", "placeholder": "Until revoked / Specific date / Upon principal's death", "help": "When POA ends"},
        {"key": "third_party_reliance", "label": "Third Party Reliance", "type": "textarea", "placeholder": "Third parties may rely on this POA without investigation", "help": "Protection for those dealing with agent"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of Ohio", "help": "Applicable jurisdiction"},
    ],
    "Arbitration Agreement": [
        {"key": "party_a", "label": "First Party", "type": "text", "placeholder": "ABC Corporation", "help": "First party to the agreement"},
        {"key": "party_b", "label": "Second Party", "type": "text", "placeholder": "John Doe", "help": "Second party to the agreement"},
        {"key": "relationship", "label": "Relationship/Context", "type": "textarea", "placeholder": "Employment relationship, business contract, consumer agreement", "help": "What relationship this covers"},
        {"key": "covered_disputes", "label": "Covered Disputes", "type": "textarea", "placeholder": "All disputes arising from employment, including discrimination, wage claims", "help": "What types of disputes are covered"},
        {"key": "excluded_disputes", "label": "Excluded Disputes", "type": "textarea", "placeholder": "Workers compensation, unemployment, trade secrets/injunctions", "help": "What is NOT covered"},
        {"key": "arbitration_rules", "label": "Arbitration Rules", "type": "text", "placeholder": "AAA Employment Rules / JAMS / CPR", "help": "Which rules will govern"},
        {"key": "arbitrator_selection", "label": "Arbitrator Selection", "type": "textarea", "placeholder": "Single arbitrator, mutually agreed or selected by AAA", "help": "How arbitrator is chosen"},
        {"key": "location", "label": "Arbitration Location", "type": "text", "placeholder": "County where employee works / Company headquarters", "help": "Where arbitration will occur"},
        {"key": "cost_allocation", "label": "Cost Allocation", "type": "textarea", "placeholder": "Company pays arbitrator fees, each party pays own attorney fees", "help": "Who pays what costs"},
        {"key": "discovery", "label": "Discovery", "type": "text", "placeholder": "Limited discovery as agreed / Full discovery", "help": "Scope of pre-hearing discovery"},
        {"key": "class_action_waiver", "label": "Class Action Waiver", "type": "text", "placeholder": "Parties waive right to class or collective actions", "help": "Individual arbitration only"},
        {"key": "confidentiality", "label": "Confidentiality", "type": "text", "placeholder": "Arbitration proceedings are confidential", "help": "Privacy of process"},
        {"key": "appeal_rights", "label": "Appeal Rights", "type": "text", "placeholder": "Award is final and binding, limited judicial review", "help": "Ability to challenge award"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "Federal Arbitration Act", "help": "Applicable law"},
    ],
    "Website Terms of Service": [
        {"key": "company_name", "label": "Company Name", "type": "text", "placeholder": "WebTech Inc.", "help": "Website owner/operator"},
        {"key": "website_url", "label": "Website URL", "type": "text", "placeholder": "https://www.example.com", "help": "Website address"},
        {"key": "effective_date", "label": "Effective Date", "type": "date", "help": "When these terms take effect"},
        {"key": "acceptance", "label": "Acceptance of Terms", "type": "textarea", "placeholder": "By accessing this website, you agree to these terms", "help": "How users agree"},
        {"key": "services_description", "label": "Services/Content Description", "type": "textarea", "placeholder": "E-commerce platform, informational content, user forums", "help": "What the website provides"},
        {"key": "user_obligations", "label": "User Obligations", "type": "textarea", "placeholder": "Accurate information, lawful use, respect for others, no spamming", "help": "What users must/must not do"},
        {"key": "prohibited_uses", "label": "Prohibited Uses", "type": "textarea", "placeholder": "Illegal activity, hacking, harassment, infringement, malware", "help": "Forbidden activities"},
        {"key": "intellectual_property", "label": "Intellectual Property", "type": "textarea", "placeholder": "All content is copyrighted, users may not reproduce without permission", "help": "IP rights and restrictions"},
        {"key": "user_content", "label": "User-Generated Content", "type": "textarea", "placeholder": "Users grant license to use posted content, retain ownership", "help": "Rights to user submissions"},
        {"key": "disclaimers", "label": "Disclaimers", "type": "textarea", "placeholder": "AS-IS, no warranties, informational purposes only", "help": "Disclaimers of liability"},
        {"key": "limitation_of_liability", "label": "Limitation of Liability", "type": "textarea", "placeholder": "Not liable for indirect damages, limited to $100", "help": "Caps on company liability"},
        {"key": "privacy_policy_link", "label": "Privacy Policy", "type": "text", "placeholder": "See our Privacy Policy at [URL]", "help": "Link to privacy policy"},
        {"key": "dispute_resolution", "label": "Dispute Resolution", "type": "textarea", "placeholder": "Binding arbitration, New York jurisdiction", "help": "How disputes are handled"},
        {"key": "modifications", "label": "Modification Rights", "type": "text", "placeholder": "We may update these terms at any time", "help": "Ability to change terms"},
        {"key": "termination", "label": "Termination", "type": "textarea", "placeholder": "We may suspend or terminate accounts for violations", "help": "Account termination rights"},
        {"key": "governing_law", "label": "Governing Law", "type": "text", "placeholder": "State of New York", "help": "Applicable jurisdiction"},
    ],
}
