[global]
developmentMode = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f8f7"
textColor = "#111111"
font = "sans serif"
